Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System;
namespace GSM.Models{
    [Table("Categories")]
    public class Category{
        [Key]
        public int CategoryID { get; set; }
        [DisplayName("% Vàng")]
        public string CategoryName { get; set; }
        [DisplayName("Tổng trọng lượng")]
        public double TotalWeight { get; set; }
        [DisplayName("Đơn giá")]
        public decimal UnitPrice { get; set; }
        [DisplayName("Thành tiền")]
        public decimal IntoMoney { get; set; }
        
    }
}

Controllers/CategoryController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSM.Data;
using GSM.Models;

namespace GSM.Controllers
{
    public class CategoryController : Controller
    {
        private readonly GSMDbContext _context;
        public CategoryController(GSMDbContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }
        public IActionResult ImportGoods()
        {
            ViewData["CategoryID"] = new SelectList(_context.Invoice, "CategoryID", "CategoryName");
            return View();
        }
        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryID,CategoryName,TotalWeight,UnitPrice,IntoMoney")] Category category)
        {
            if(category.TotalWeight==null){
                category.TotalWeight = 0;
            }
            if(category.UnitPrice==null){
                category.UnitPrice = 0;
            }
            category.IntoMoney = Convert.ToDecimal(category.TotalWeight) * category.UnitPrice;

            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryID,CategoryName,TotalWeight,UnitPrice,IntoMoney")] Category category)
        {
            if (id != category.CategoryID)
            {
                return NotFound();
            }
            if(category.TotalWeight==null){
                category.TotalWeight = 0;
            }
            if(category.UnitPrice==null){
                category.UnitPrice = 0;
            }
            category.IntoMoney = Convert.ToDecimal(category.TotalWeight) * category.UnitPrice;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryID == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult UpdateDataCategory()
        {
            DataNormalization dataNor = new DataNormalization();
            dataNor.CategoryDataNormalization();
            return RedirectToAction(nameof(Index));
        }
        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryID == id);
        }
    }
}

Controllers/ImportInvoiceController.cs
using System.Collections.Generic;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using GSM.Models;
using GSM.Data;
using Microsoft.EntityFrameworkCore;

namespace GSM.Controllers
{
    public class ImportInvoiceController : Controller
    {
        private readonly GSMDbContext _context;
        private readonly StringProcess strPro = new StringProcess();

        public ImportInvoiceController(GSMDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.ImportInvoice.OrderByDescending(m => m.CreateDate).ToListAsync());
        }
        public IActionResult Create(){
            ViewData["CategoryID"] = new SelectList(_context.Category, "CategoryID", "CategoryName");
            var listPro = _context.Product.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult Create(List<ImportInvoiceDetail> listInv){
            //save information of ImportInvoice
            ImportInvoice impInvoice = new ImportInvoice();
            impInvoice.CreateDate = DateTime.Now;
            impInvoice.TotalMoney = 0;
            _context.Add(impInvoice);
            _context.SaveChangesAsync();
            //get ImportInvoiceId
            var impInvID = _context.ImportInvoice.OrderByDescending(m => m.ImportInvoiceID).FirstOrDefault().ImportInvoiceID;
            //save information of invoice detail by InvoiceID
            foreach(ImportInvoiceDetail invD in listInv)
            {
                invD.ImportInvoiceID = impInvID;
                _context.Add(invD);
            }
            _context.SaveChangesAsync();
            //get list ImportInvoiceDetail by ImportInvoiceID
            var impInvDList = _context.ImportInvoiceDetail.Where(m => m.ImportInvoiceID == impInvID).ToList();
            decimal totalMoney = 0;
            for (var i = 0; i < impInvDList.Count; i++)
            {
                var impInvDetail = _context.ImportInvoiceDetail.Find(impInvDList[i].InvoiceDetailID);
                impInvDetail.IntoMoney = Convert.ToDecimal(impInvDetail.SumWeight) * impInvDetail.GoldUnitPrice;
                totalMoney += impInvDetail.IntoMoney;
                _context.Update(impInvDetail);
                _context.SaveChanges();
            }
            //update TotalMoney of ImportInvoice
            var impInv = _context.ImportInvoice.Find(impInvID);
            impInv.TotalMoney = totalMoney;
            _context.Update(impInv);
            _context.SaveChanges();
            //update TotalWeight to Category
            for (var i = 0; i < impInvDList.Count; i++)
            {
                var sumWeight = impInvDList[i].SumWeight;
                var categoryId = impInvDList[i].CategoryID;
                var category = _context.Category.Find(categoryId);
                category.TotalWeight += sumWeight;
                _context.Update(category);
                _context.SaveChanges(); 
            }
            return Json("Tạo mới hoá đơn thành công.");
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var impInvoice = await _context.ImportInvoice
                .FirstOrDefaultAsync(m => m.ImportInvoiceID == id);
            if (impInvoice == null)
            {
                return NotFound();
            }

            return View(impInvoice);
        }
        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //remove ImportInvoiceDetail
            var list = await _context.ImportInvoiceDetail.Where(m => m.ImportInvoiceID == id).ToListAsync();
            _context.RemoveRange(list);
            await _context.SaveChangesAsync();
            //remove ImportInvoice
            var impInvoice = await _context.ImportInvoice.FindAsync(id);
            _context.ImportInvoice.Remove(impInvoice);
            await _context.SaveChangesAsync();
            return RedirectToAction("CategoryDataNormalization","DataNormalization");
        }
    }
}

Views/Category/Create.cshtml
@model GSM.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo mới loại vàng</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalWeight" class="control-label"></label>
                <input asp-for="TotalWeight" class="form-control" />
                <span asp-validation-for="TotalWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
                <a class ="btn btn-success" asp-action="Index">Quay về danh sách</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/Delete.cshtml
@model GSM.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IntoMoney)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IntoMoney)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Category/Edit.cshtml
@model GSM.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h2>Cập nhật thông tin loại vàng</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryID" />
            <input type="hidden" asp-for="TotalWeight" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-success" asp-action="Index">Quay lại danh sách</a>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/ImportGoods.cshtml
@model GSM.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class ="form-control" asp-items="ViewBag.InvoiceID"></select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalWeight" class="control-label"></label>
                <input asp-for="TotalWeight" class="form-control" />
                <span asp-validation-for="TotalWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Category/Index.cshtml
@model IEnumerable<GSM.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h1>Thống Kê</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Tạo mới loại vàng</a>
    <a class="btn btn-success" asp-controller="ImportInvoice" asp-action="Create">Nhập hàng</a>
    <a class="btn btn-info" asp-controller="DataNormalization" asp-action="CategoryDataNormalization">Chuẩn hoá dữ liệu</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IntoMoney)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalWeight)
            </td>
            <td>
                @string.Format("{0:0,0}", item.UnitPrice)
            </td>
            <td>
                @string.Format("{0:0,0}", item.IntoMoney)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CategoryID">Sửa</a> |
                <a asp-action="Delete" asp-route-id="@item.CategoryID">Xoá</a>
            </td>
        </tr>
}
    </tbody>
</table>