Models/Invoice.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.Collections.Generic;
using System;
namespace GSM.Models{
    [Table("Invoice")]
    public class Invoice{
        [Key]
        [DisplayName("STT")]
        public int InvoiceID { get; set; }
        [DisplayName("Họ tên khách hàng")]
        public string CustomerName { get; set; }
        [DisplayName("Số hoá đơn")]
        public string InvoiceNumber { get; set; }
        [DisplayName("Địa chỉ")]
        public string Address { get; set; }
        [DisplayName("Điện thoại")]
        public string PhoneNumber { get; set; }
        [DisplayName("Ngày")]
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public DateTime CreateDate { get; set; }
        [DisplayName("Mã số")]
        public string InvoiceCode { get; set; }
        [DisplayName("Tổng tiền")]
        [DisplayFormat(DataFormatString = "{0}")]
        public decimal TotalMoney { get; set; }
        public bool IsPaid { get; set; }
        public ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}

Controllers/InvoiceDetailController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GSM.Models;
using GSM.Data;

namespace GSM.Controllers
{
    public class InvoiceDetailController : Controller
    {
        private readonly GSMDbContext _context;

        public InvoiceDetailController(GSMDbContext context)
        {
            _context = context;
        }

        // GET: InvoiceDetail/Create
        public IActionResult Create()
        {
            ViewData["InvoiceID"] = new SelectList(_context.Invoice, "InvoiceID", "InvoiceID");
            return View();
        }

        // POST: InvoiceDetail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InvoiceDetailID,InvoiceID,ProductName,SumWeight,PercentGold,GoldWeight,GoldUnitPrice,GemstoneWeight,GemstoneUnitPrice,CraftingWages,IntoMoney")] InvoiceDetail invoiceDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invoiceDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Invoice");
            }
            ViewData["InvoiceID"] = new SelectList(_context.Invoice, "InvoiceID", "InvoiceID", invoiceDetail.InvoiceID);
            return View(invoiceDetail);
        }

        // GET: InvoiceDetail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceDetail = await _context.InvoiceDetail.FindAsync(id);
            if (invoiceDetail == null)
            {
                return NotFound();
            }
            ViewBag.invNumber = _context.Invoice.Where(m => m.InvoiceID == invoiceDetail.InvoiceID).First().InvoiceNumber;
            return View(invoiceDetail);
        }

        // POST: InvoiceDetail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InvoiceDetailID,InvoiceID,ProductName,SumWeight,PercentGold,GoldWeight,GoldUnitPrice,GemstoneWeight,GemstoneUnitPrice,CraftingWages,IntoMoney")] InvoiceDetail invoiceDetail)
        {
            if (id != invoiceDetail.InvoiceDetailID)
            {
                return NotFound();
            }
            var invID = _context.InvoiceDetail.Find(id).InvoiceID;
            if(invID!=invoiceDetail.InvoiceDetailID)
            {
                return NotFound();
            }
            try{
                // var IntoMoney = GoldWeight * GoldUnitPrice + GemstoneWeight * GemstoneUnitPrice + CraftingWages;
                invoiceDetail.IntoMoney = invoiceDetail.CraftingWages + Convert.ToDecimal(invoiceDetail.GoldWeight * Convert.ToDouble(invoiceDetail.GoldUnitPrice) + invoiceDetail.GemstoneWeight * Convert.ToDouble(invoiceDetail.GemstoneUnitPrice));
            }
            catch{
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoiceDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceDetailExists(invoiceDetail.InvoiceDetailID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Detail","Invoice", invoiceDetail.InvoiceID);
            }
            return View(invoiceDetail);
        }

        // GET: InvoiceDetail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceDetail = await _context.InvoiceDetail
                .Include(i => i.Invoice)
                .FirstOrDefaultAsync(m => m.InvoiceDetailID == id);
            if (invoiceDetail == null)
            {
                return NotFound();
            }

            return View(invoiceDetail);
        }

        // POST: InvoiceDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoiceDetail = await _context.InvoiceDetail.FindAsync(id);
            _context.InvoiceDetail.Remove(invoiceDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Invoice");
        }

        private bool InvoiceDetailExists(int id)
        {
            return _context.InvoiceDetail.Any(e => e.InvoiceDetailID == id);
        }
    }
}

Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GSM.Models;
using GSM.Data;

namespace GSM.Controllers
{
    public class ProductController : Controller
    {
        private readonly GSMDbContext _context;

        public ProductController(GSMDbContext context)
        {
            _context = context;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,ProductName")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,ProductName")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductID == id);
        }
    }
}

Controllers/SaleController.cs
using System.Collections.Generic;
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using GSM.Models;
using GSM.Data;
namespace GSM.Controllers
{
    public class SaleController : Controller
    {
        private readonly GSMDbContext _context;
        private readonly StringProcess strPro = new StringProcess();

        public SaleController(GSMDbContext context)
        {
            _context = context;
        }
        public IActionResult Create(){
            var model = _context.Invoice.ToList();
            if(model.Count() == 0) ViewBag.InVoiceKey = "N001";
            else {
                var latestKey = model.OrderByDescending(m => m.InvoiceNumber).FirstOrDefault().InvoiceNumber;
                ViewBag.InVoiceKey = strPro.GenerateKey(latestKey);
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ProductID", "ProductName");

            var listProduct = _context.Product.Select(m => m.ProductName).ToArray();
            //return list product to view
            ViewData["ListProduct"] = listProduct;
            ViewData["Category"] = new SelectList(_context.Category, "CategoryID", "CategoryName");

            var listPro = _context.Product.ToList();
            return View();
        }
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Create(Invoice invoice, List<InvoiceDetail> listInv){
        //     //save information of invoice
        //     _context.Add(invoice);
        //     await _context.SaveChangesAsync();
        //     //get InvoiceId
        //     var invID = _context.Invoice.OrderByDescending(m => m.InvoiceID).FirstOrDefault().InvoiceID;
        //     //save information of invoice detail by InvoiceID
        //     foreach(InvoiceDetail invD in listInv)
        //     {
        //         invD.InvoiceID = invID;
        //         _context.Add(invD);
        //     }
        //     await _context.SaveChangesAsync();
        //     //update IsPaid of Invoice = True
        //     var inv = await _context.Invoice.FindAsync(invID);
        //     if(inv!=null){
        //         inv.IsPaid = true;
        //         _context.Update(inv);
        //         await _context.SaveChangesAsync();
        //     }
        //     return RedirectToAction("Index","Invoice");
        // }
        [HttpPost]
        public IActionResult Create(Invoice invoice, List<InvoiceDetail> listInv){
            //save information of invoice
            invoice.CreateDate = DateTime.Now;
            _context.Add(invoice);
            _context.SaveChangesAsync();
            //get InvoiceId
            var invID = _context.Invoice.OrderByDescending(m => m.InvoiceID).FirstOrDefault().InvoiceID;
            //save information of invoice detail by InvoiceID
            foreach(InvoiceDetail invD in listInv)
            {
                invD.InvoiceID = invID;
                _context.Add(invD);
            }
            _context.SaveChangesAsync();
            //update TotalWeight to Category
            //--get list InvoiceDetail by InvoiceID
            var invDetailList = _context.InvoiceDetail.Where(m => m.InvoiceID == invID).ToList();
            for (var i = 0; i < invDetailList.Count; i++)
            {
                var percentGold = invDetailList[i].PercentGold;
                var goldWeight = invDetailList[i].GoldWeight;
                var categoryID = _context.Category.Where(m => m.CategoryName == percentGold).First().CategoryID;
                var category = _context.Category.Find(categoryID);
                category.TotalWeight = category.TotalWeight-goldWeight;
                _context.Update(category);
                _context.SaveChanges();
            }
            //update IsPaid of Invoice = True
            var inv = _context.Invoice.Find(invID);
            if(inv!=null){
                inv.IsPaid = true;
                _context.Update(inv);
                _context.SaveChangesAsync();
            }
            //return RedirectToAction("Index","Invoice");
            return Json("Tạo mới hoá đơn thành công.");
        }

        // [HttpPost]
        // public JsonResult Create(Invoice invoice, List<InvoiceDetail> listInv){
        //     var mess = "";
        //     mess+= invoice.CustomerName + "-" + invoice.InvoiceNumber + "-" + invoice.Address + "-" + invoice.PhoneNumber + "-" + invoice.CreateDate + "-" + invoice.InvoiceCode + "-" + invoice.TotalMoney + "-" + invoice.IsPaid + ";\n";
        //     foreach(InvoiceDetail invD in listInv)
        //     {
        //         mess+= invD.ProductName + "-" + invD.SumWeight + "-" + invD.PercentGold + "-" + invD.GoldWeight + "-" + invD.GoldUnitPrice + "-" + invD.GemstoneWeight + "-" + invD.GemstoneUnitPrice + "-" + invD.CraftingWages + "-" + invD.IntoMoney;
        //     }
        //     return Json(mess);
        // }
    }
}

Views/Invoice/Delete.cshtml
@model GSM.Models.Invoice

@{
    ViewData["Title"] = "Delete";
}

<h3>Bạn có muốn xoá thông tin hoá đơn?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvoiceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.FormatValue(Model.CreateDate, "{0:dd-MM-yyyy}")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalMoney)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalMoney)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="InvoiceID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Quay về danh sách</a>
    </form>
</div>

Views/Invoice/Detail.cshtml
@model IEnumerable<GSM.Models.InvoiceDetail>

@{
    ViewData["Title"] = "Detail";
}

<h3>Chi tiết hoá đơn: @ViewBag.informationInvoice</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SumWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PercentGold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GoldWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GoldUnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GemstoneWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GemstoneUnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CraftingWages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IntoMoney)
            </th>
            @* <th></th> *@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SumWeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentGold)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GoldWeight)
            </td>
            <td>
                @string.Format("{0:0,0}", item.GoldUnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GemstoneWeight)
            </td>
            <td>
                @string.Format("{0:0,0}", item.GemstoneUnitPrice)
            </td>
            <td>
                @string.Format("{0:0,0}", item.CraftingWages)
            </td>
            <td>
                @string.Format("{0:0,0}", item.IntoMoney)
            </td>
            @* <td>
                <a asp-controller="InvoiceDetail" asp-action="Edit" asp-route-id="@item.InvoiceID">Sửa</a>
                <a asp-controller="InvoiceDetail" asp-action="Delete" asp-route-id="@item.InvoiceID">Xoá</a>
            </td> *@
        </tr>
}
    </tbody>
</table>

Views/Invoice/Edit.cshtml
@model GSM.Models.Invoice

@{
    ViewData["Title"] = "Edit";
}

<h4>Sửa thông tin hoá đơn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InvoiceID" />
            <input type="hidden" asp-for="InvoiceNumber" />
            <input type="hidden" asp-for="TotalMoney" />
            <input type="hidden" asp-for="IsPaid" />
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-success" asp-action="Index">Danh sách hoá đơn</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Invoice/Index.cshtml
@model IEnumerable<GSM.Models.Invoice>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách hoá đơn</h1>

<div class="row mb-2">
    <a asp-controller="Sale" asp-action="Create" class="btn btn-primary mr-3">Tạo hoá đơn mới</a>
    <a asp-controller="Product" asp-action="Index" class="btn btn-success mr-3">Quản lý sản phẩm</a>
    <a asp-controller="Category" asp-action="Index" class="btn btn-info">Quản lý loại vàng</a>
</div>
<div class="row mb-2 p-2 border rounded border-primary">
    <form asp-action="Index">
        <label>Từ ngày: </label><input type="date" name="startTime" class="ml-2"/>
        <label>Đến ngày: </label><input type="date" name="finishTime" class="ml-2"/>
        <input type="text" placeholder="Nhập từ khoá muốn tìm kiếm" name="key"/>
        <input type="submit" class="btn btn-primary" value="Tìm kiếm"/>
    </form>
</div>

<table class="table" id="InvoiceTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalMoney)
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.FormatValue(item.CreateDate, "{0:dd-MM-yyyy}")
            </td>
            <td>
                @string.Format("{0:0,0}", item.TotalMoney)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.InvoiceID">Sửa</a> |
                <a asp-action="Delete" asp-route-id="@item.InvoiceID">Xoá</a> |
                <a asp-action="Detail" asp-route-id="@item.InvoiceID">Chi tiết hoá đơn</a> |
                <form asp-action="PrintInvoice">
                    <input type="hidden" name="invoiceID" value="@item.InvoiceID"/>
                    <input type="submit" class="btn btn-primary" value="In hoá đơn"/>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            ReWriteNumber();
        });
        function ReWriteNumber() {
            var MyTable = document.getElementById('InvoiceTable');
            var rowCount = $("#InvoiceTable tr").length;
            for (let i = 1; i < rowCount; i++) {
                MyTable.rows[i].cells[0].innerHTML = i;
            }
        }
    </script>
}